### PR TITLE
Adding it localization

### PR DESCRIPTION
**Pull request by flavio-a**
I'd like to contribute to Italian localization, but Italian is not available on crowdin, and if I understood correctly this stuff is needed for the localization.

### CODE REVIEW

**Comment by TheMulhima** [comment]
Thanks for your interest. I've added the Italian language on crowdin so you'll be able to start contributing. I'll merge this pr once the translations are ready

**Comment by flavio-a** [comment]
Is there a way I can build Lumafly with the it translation myself before release? Just to make sure everything is kinda consistent and makes sense, it's not so easy to translate some stuff without context.

**Comment by flavio-a** [comment]
Ok I think I'm done with the translation, if you wanna merge and stuff

**Comment by flavio-a** [comment]
Any updates on this?

**Comment by TheMulhima** [comment]
Hey, sorry I've been really busy lately. I'll hopefully try to release it by end of July.

**Pull request merged**
